version: '3.5'

services:

  stt-service-manager:
    image: my_stt_manager:latest
    depends_on:
      - mongodb-stt-service-manager
    volumes:
      - ./model:/opt/model
      - ./config/nginx.conf:/opt/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/swagger.yml:/opt/swagger.yml
    ports:
      - target: 80
        published: 8080
      - target: 8001
        published: 8081

    env_file: .env
    networks:
      - linto-net

  mongodb-stt-service-manager:
    image: mongo:latest
    volumes:
      - ./model/dbdata:/data/db
      - ./config/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: linSTTAdmin
    networks:
      - linto-net

networks:
    internal:
    linto-net:
       external: true
