version: '3.5'

services:

  stt-service-manager:
    image: lintoai/linto-platform-stt-server-manager:latest
    depends_on:
      - mongodb-stt-service-manager
    volumes:
      - ${LINTO_SHARED_MOUNT}:/opt/model
      - ./config/nginx.conf:/opt/nginx/nginx.conf
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - target: 8000
        published: 8000
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
    healthcheck:
      interval: 15s
      timeout: 10s
      retries: 4
      start_period: 50s
    env_file: .env
    command: # Overrides CMD specified in dockerfile (none here, handled by entrypoint)
      - --run-cmd=npm run start
    networks:
      - linto-net

  mongodb-stt-service-manager:
    image: mongo:latest
    volumes:
      - ${LINTO_SHARED_MOUNT}/dbdata:/data/db
      - ${LINTO_SHARED_MOUNT}/dbbackup:/data/backup
      - ./config/seed:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: linSTTAdmin
    networks:
      - linto-net

networks:
    internal:
    linto-net:
       external: true
